# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    branches: [main, master, multigroup_test]
  pull_request:
    branches: [main, master, multigroup_test]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_FORCE_SUGGESTS_: false
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install dependencies
        run: |
          install.packages(c("doParallel","foreach","logging","mixsqp"))
          install.packages(c("magrittr","tibble","dplyr","ggplot2","cowplot"))
          install.packages(c("ggrepel","readr","data.table"))
          install.packages(c("RSQLite","locuszoomr","pgenlibr","Rfast"))
          install.packages(c("knitr","rmarkdown","testthat","BiocManager"))
          install.packages(c("crayon","rcmdcheck"))
          BiocManager::install("GenomeInfoDb",ask = FALSE)
          BiocManager::install("ensembldb",ask = FALSE)
          BiocManager::install("AnnotationFilter",ask = FALSE)
          BiocManager::install("EnsDb.Hsapiens.v86",ask = FALSE)
        shell: Rscript {0}
      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual","--ignore-vignettes"),
                               error_on = "error",
                               build_args = "--no-build-vignettes")
        shell: Rscript {0}


